const express=require('express');
const {register,login,me,updateProfile,forgotPassword,resetPassword}=require('../controllers/authController');
const {requireAuth}=require('../middleware/auth');
const router=express.Router();
router.post('/register',register);
router.post('/login',login);
router.post('/forgot-password',forgotPassword);
router.post('/reset-password',resetPassword);
router.get('/me',requireAuth,me);\nrouter.patch('/me',requireAuth,updateProfile);
module.exports=router;
